import {
  Bold,
  Italic,
  Strikethrough,
  Underline,
  Subscript,
  Superscript,
  Heading1,
  Heading2,
  Heading3,
  Code,
  SquareCode,
  Sigma,
  Pi,
  List,
  ListOrdered,
  Quote,
  Table,
  Minus,
  Undo,
  Redo,
  type LucideIcon,
} from "lucide-react"

export interface ToolbarActionDef {
  id: string
  label: string
  icon: LucideIcon
  shortcut?: string
  group: "history" | "heading" | "inline" | "code" | "math" | "list" | "insert"
  type: "inline" | "block" | "heading" | "custom"
  prefix?: string
  suffix?: string
  fallback?: string
  level?: 1 | 2 | 3
}

export const TOOLBAR_ACTIONS: ToolbarActionDef[] = [
  {
    id: "undo",
    label: "Undo",
    icon: Undo,
    shortcut: "Mod+Z",
    group: "history",
    type: "custom",
  },
  {
    id: "redo",
    label: "Redo",
    icon: Redo,
    shortcut: "Mod+Y",
    group: "history",
    type: "custom",
  },

  {
    id: "h1",
    label: "Heading 1",
    icon: Heading1,
    shortcut: "Mod+Alt+1",
    group: "heading",
    type: "heading",
    level: 1,
    fallback: "Heading 1",
  },
  {
    id: "h2",
    label: "Heading 2",
    icon: Heading2,
    shortcut: "Mod+Alt+2",
    group: "heading",
    type: "heading",
    level: 2,
    fallback: "Heading 2",
  },
  {
    id: "h3",
    label: "Heading 3",
    icon: Heading3,
    shortcut: "Mod+Alt+3",
    group: "heading",
    type: "heading",
    level: 3,
    fallback: "Heading 3",
  },

  {
    id: "bold",
    label: "Bold",
    icon: Bold,
    shortcut: "Mod+B",
    group: "inline",
    type: "inline",
    prefix: "**",
    suffix: "**",
    fallback: "bold text",
  },
  {
    id: "italic",
    label: "Italic",
    icon: Italic,
    shortcut: "Mod+I",
    group: "inline",
    type: "inline",
    prefix: "*",
    suffix: "*",
    fallback: "italic text",
  },
  {
    id: "underline",
    label: "Underline",
    icon: Underline,
    shortcut: "Mod+U",
    group: "inline",
    type: "inline",
    prefix: "<u>",
    suffix: "</u>",
    fallback: "underlined text",
  },
  {
    id: "strikethrough",
    label: "Strikethrough",
    icon: Strikethrough,
    shortcut: "Mod+Shift+X",
    group: "inline",
    type: "inline",
    prefix: "~~",
    suffix: "~~",
    fallback: "strikethrough text",
  },
  {
    id: "subscript",
    label: "Subscript",
    icon: Subscript,
    shortcut: "Mod+Alt+,",
    group: "inline",
    type: "inline",
    prefix: "<sub>",
    suffix: "</sub>",
    fallback: "subscript",
  },
  {
    id: "superscript",
    label: "Superscript",
    icon: Superscript,
    shortcut: "Mod+Alt+.",
    group: "inline",
    type: "inline",
    prefix: "<sup>",
    suffix: "</sup>",
    fallback: "superscript",
  },

  {
    id: "inline-code",
    label: "Inline Code",
    icon: Code,
    shortcut: "Mod+Alt+C",
    group: "code",
    type: "inline",
    prefix: "`",
    suffix: "`",
    fallback: "code",
  },
  {
    id: "code-block",
    label: "Fenced Code Block",
    icon: SquareCode,
    shortcut: "Mod+Alt+Shift+C",
    group: "code",
    type: "block",
    prefix: "\n```java\n",
    suffix: "\n```\n",
    fallback: "// Write code here",
  },

  {
    id: "inline-math",
    label: "Inline Math (LaTeX)",
    icon: Pi,
    shortcut: "Mod+Alt+M",
    group: "math",
    type: "inline",
    prefix: "$",
    suffix: "$",
    fallback: "O(n \\log n)",
  },
  {
    id: "block-math",
    label: "Block Math (LaTeX)",
    icon: Sigma,
    shortcut: "Mod+Alt+Shift+M",
    group: "math",
    type: "block",
    prefix: "\n$$\n",
    suffix: "\n$$\n",
    fallback: "\\sum_{i=1}^{n} x_i",
  },

  {
    id: "bullet-list",
    label: "Bullet List",
    icon: List,
    shortcut: "Mod+Alt+U",
    group: "list",
    type: "block",
    prefix: "\n- ",
    suffix: "\n",
    fallback: "List item",
  },
  {
    id: "number-list",
    label: "Numbered List",
    icon: ListOrdered,
    shortcut: "Mod+Alt+O",
    group: "list",
    type: "block",
    prefix: "\n1. ",
    suffix: "\n",
    fallback: "First item",
  },

  {
    id: "quote",
    label: "Quote",
    icon: Quote,
    shortcut: "Mod+Alt+Q",
    group: "insert",
    type: "block",
    prefix: "\n> ",
    suffix: "\n",
    fallback: "Important note or quote",
  },
  {
    id: "table",
    label: "Table",
    icon: Table,
    shortcut: "Mod+Alt+T",
    group: "insert",
    type: "block",
    prefix:
      "\n| Column 1 | Column 2 | Column 3 |\n| :--- | :---: | ---: |\n| Item 1 | Value 1 | Details 1 |\n| Item 2 | Value 2 | Details 2 |\n",
    suffix: "",
    fallback: "",
  },
  {
    id: "hr",
    label: "Horizontal Divider",
    icon: Minus,
    shortcut: "Mod+Alt+D",
    group: "insert",
    type: "block",
    prefix: "\n---\n",
    suffix: "",
    fallback: "",
  },
]
